#+TITLE: Contribute
/Instructions for how to contribute to the project/
* Overview
The West House Songbook is free software, which means that anyone is free to enjoy it, share it, copy it, modify it, and otherwise benefit from it. If you feel inspired, throw some brain cells in this direction and add your brilliance to the project. Contributions are wholeheartedly welcome.

This page is meant to help you figure out how to contribute. If you're at all interested please read through, but also feel free to email Jason (~info [at] jasonreeder.com~) with your ideas and questions.
* Help Wanted
There are many ways to help, from adding new songs and correcting lyrics in existing songs, to adding new features and improving the UI. Notes for future tasks are documented and organized in [[file:todos.org][todos.org]].

The source code for the songs is available in the directory [[file:../songs/production][songs/production/]], and any changes to the chords or lyrics there will be reflected in the app.
* Running Locally
Running locally is a good way to get to know your neighborhood and exercise. Running this application locally is a good way to test and see what your changes and additions look like. That can be done on your own computer, or on a virtual machine such as

If any of this is confusing, get in touch.
** 0. Make sure you can run Python 3
This app requires Python 3 to run. To check whether you have Python 3, attempt opening the interpreter by typing ~python3~ on the command line.

If you do not have Python 3 installed, here are notes:
*** With Anaconda
- The Anaconda documentation describes how to run Python 3 even if you'd prefer to keep Python 2 the default: [[http://conda.pydata.org/docs/py2or3.html][Anaconda Docs: Managing Python]]
  - The section ~Create a Python 3.5 environment~ is particularly relevant
** 1. Copy the files
*** Option 1: From Github
1. Return to the main page of the repository: [[https://github.com/jsonreeder/whsongbook][link]]
2. Click ~Clone or download~
3. Click ~Download ZIP~
4. Unzip the folder
*** Option 2: From the command line
1. Clone the repository using git:
   - ~git clone https://github.com/jsonreeder/whsongbook.git~
** 2. Start a Virtual Environment (Optional)
Starting a virtual environment will contain the packages installed later
1. Make sure you have ~virtualenv~:
   1. Check:
     - ~virtualenv --version~
   2. If you don't have it, install it:
     - ~pip install virtualenv~
2. Create the environment:
  - ~virtualenv env~
3. Start the environment:
  - ~source env/bin/activate~
** 3. Install the requirements
1. Open up a terminal emulator and make sure that you are in the directory you downloaded in the step above
2. Make sure that you have a version of Python 3
3. Install the requirements listed in ~requirements.txt~:
   - ~pip3 install -r requirements.txt~
** 4. Run the app
- Execute the ~run.py~ script:
  - ~python3 run.py~
** 5. Use the app in your browser
- Go to the following URL in any browser: ~http://0.0.0.0:8080/~
- You should see the app
- If you don't, something above went wrong. Again, don't hesitate to be in touch.
* Add Songs
One of the most useful things to do is to add new song transcriptions. Here are some thoughts about how to do that.
** Logistics
- Check out the existing songs in [[file:../songs/production][songs/production]] to learn the format
- Add your new transcription to that folder
- Rerun the app
- If there are any errors in your transcription, the app will fail to start, and the errors will be logged in the file ~errors.log~
- In some cases, failing songs throw the app into a loop. If that happens, kill the "run" command by typing ~ctrl - c~ in your terminal, and note that the same errors will be listed multiple times in the log.
** Style
There is a style guide for song transcriptions: [[file:style.org][style.org]].
* Making Pull Requests
Here are instructions for how to submit your additions to production
1) Fork this repository
2) Make and commit changes on your fork
3) Submit a pull request to the original repository with your changes
4) Jason ([[github.com/jsonreeder/][jsonreeder]]) will accept the changes if they look good, or write comments if anything else is needed to incorporate them
