#+TITLE: Syle Guide
* Song Format
The songs are documented in a basic syntax following these parameters:
- Lyrics are displayed as written. Currently no markup is supported.
- Chords are written in the syntax defined by LilyPond, a spectacular music engraving markup language:
  - LilyPond: [[http://lilypond.org/doc/v2.19/Documentation/notation/common-chord-modifiers][Common Chord Modifiers]]
  - LilyPond: [[http://lilypond.org/doc/v2.19/Documentation/notation/chord-mode][Chord Mode]]
- For a chord to be aligned above a given word, that chord should be in brackets immediately preceding it:
  : [c]Love of mine some day [a:m]you will die
  - This syntax was inspired by Chordii
- Metadata is documented in line with Python variable definitions:
  : title = "I Will Follow You Into the Dark"
  : artist = "Death Cab for Cutie"
  : capo = 5
  : year = 2005
  : genres = ["indie"]
* Emacs
The Emacs Major Mode provides basic syntax highlighting in line with the specifications above: [[file:emacs_major-mode/song-mode.lisp][song-mode.lisp]].
* Chord Placement
- Chord placement means the alignment of the chords with the lyrics.
- The guiding principle with chord placement is to be as simple to read as possible while still being faithful to the original timing.
- Chords should be placed immediately before the syllable during which they occur.
- If the original line is synchopated, it can be hard to determine exactly where the chord should go. In cases of ambiguity, choose the alignment that will be simplest and easiest to read.
- When the lyrics for a given line start after the first chord, the first lyric should be preceded by three spaces.
  - Correct:
    : [g]   I pulled into [b:m]Nazareth, was [c]feeling about half past [g]dead
* Punctuation
- The primary function of punctuation in the lyrics is to indicate rests within lines.
- The guiding principle with punctuation is to remove it unless it is helpful to the singing.
- The main exceptions are question marks (?) and exclamation marks (!). These may be included.
* Quotations
- Quotations should be indicated not by quotation marks, but by a comma and a capital.
  - Correct:
    : They said, How long can you hang around?
    : I said, A week, maybe two
  - Incorrect:
    : They said, "How long can you hang around?"
    : I said, "A week, maybe two"
* Capitalization
- The first word in each line should be capitalized.
- Song titles should have title capitalization.
  - Guide: [[http://aitech.ac.jp/~ckelly/midi/help/caps.html][ckelley]]
  - Note that this conflicts with Spotify, which capitalizes every word in titles.
  - Examples
    - Correct
      - Anyone Else but You
    - Incorrect
      - Anyone Else But You
* File Naming
- Song files should follow the convention "Title - Artist.song" with all spaces replaced by underscores "_".
- The values for ~title~ and ~artist~ in file names should match the metadata within the song itself.
* Numbers
- Numbers in lyrics should be spelled out instead of given as digits. This allows for more accurate chord placement.
- Examples
  - Correct
    - Well she was just seventeen
  - Incorrect
    - Well she was just 17
- Exceptions
  - Years (it's too awkward to read these as words)
    - ~[a:m]   I'd been that way since 19[d:m]56~
  - If the line is long and the digit would save space
* Explicit Lyrics
- The general philosophy for lyrics is that they should remain true to the original song, even when they are explicit.
- Exceptions can be made if an offending line can easily be changed without significantly altering it.
  - A line that was altered from the original:
    : I'm a-gonna stay where you sleep all day where they hung the *jerk* that invented work
  - The original:
    : I'm a-gonna stay where you sleep all day where they hung the *Turk* that invented work
* Contractions
- Contractions should be indicated by apostrophes (as in their standard spelling).
- Examples
  - Correct
    - ~Flippin' your fins you don't get too far. Legs are required for jumpin', dancin'~
  - Incorrect
    - ~Flippin your fins you dont get too far. Legs are required for jumpin, dancin~
* Repetition
- The main goal of these transcriptions is to provide an outlines outline of the songs that it quick and easy to read while playing. That is more important than providing a perfectly faithful transcription.
- Many songs end with double or triple repeats of choruses and outros. In most cases, it's preferable only to write that part twice. People can easily choose to sing the part more than once, but notating it twice can often prove boring or monotonous while singing.
- This principle also applies to introductions. If there is an instrumental introduction that is the same as the first part of the song, it does not have to be notated, since it is natural to add these in anyways.
